### ISSUE TITLE
python 报错

### ISSUE THREAD

**Issue by badboycxcc** [twfb/dark-market-spider#5]
>  sudo python chinese_forum_spider.py   
try to login...
login success
Traceback (most recent call last):
  File "/home/dark-market-spider/chinese_forum_spider.py", line 524, in <module>
    master.run_spider()
  File "/home/dark-market-spider/chinese_forum_spider.py", line 325, in run_spider
    for c_id, name in self.get_classification_url():
  File "/home/dark-market-spider/chinese_forum_spider.py", line 313, in get_classification_url
    text = text.split(
IndexError: list index out of range
>

**Comment by twfb** [comment]
应该是网站的代码改了
